
package com.charter.enterprise.updateidentity;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UpdateIdentity_PortType", targetNamespace = "http://charter.com/enterprise/updateidentity")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UpdateIdentityPortType {


    /**
     * 
     * @param body
     * @return
     *     returns com.charter.enterprise.updateidentity.UpdateIdentityResponseType
     */
    @WebMethod(operationName = "UPDATE_IDENTITY")
    @WebResult(name = "UpdateIdentityResponse", targetNamespace = "http://charter.com/enterprise/updateidentity", partName = "body")
    public UpdateIdentityResponseType updateIDENTITY(
        @WebParam(name = "UpdateIdentityRequest", targetNamespace = "http://charter.com/enterprise/updateidentity", partName = "body")
        UpdateIdentityRequestType body);

}
