
package com.charter.enterprise.customer.queryidentity;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "QueryIdentityIDMDBReqABCSImpl", targetNamespace = "http://charter.com/enterprise/customer/QueryIdentity")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QueryIdentityIDMDBReqABCSImpl {


    /**
     * 
     * @param payload
     * @return
     *     returns com.charter.enterprise.customer.queryidentity.QueryIdentityResponseType
     */
    @WebMethod(action = "process")
    @WebResult(name = "QueryIdentityResponse", targetNamespace = "http://charter.com/enterprise/customer/QueryIdentity", partName = "payload")
    public QueryIdentityResponseType process(
        @WebParam(name = "QueryIdentityRequest", targetNamespace = "http://charter.com/enterprise/customer/QueryIdentity", partName = "payload")
        QueryIdentityRequestType payload);

}
