
package com.charter.enterprise.customer.queryidentity;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "QueryIdentityIDMDBReqABCSImplBindingQSService", targetNamespace = "http://charter.com/enterprise/customer/QueryIdentity", wsdlLocation = "file:/D:/project/Git%20Lab/CSG-API/master/src/main/resources/wsdl/soa/QueryIdentity_V1.wsdl")
public class QueryIdentityIDMDBReqABCSImplBindingQSService
    extends Service
{

    private final static URL QUERYIDENTITYIDMDBREQABCSIMPLBINDINGQSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.charter.enterprise.customer.queryidentity.QueryIdentityIDMDBReqABCSImplBindingQSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.charter.enterprise.customer.queryidentity.QueryIdentityIDMDBReqABCSImplBindingQSService.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/project/Git%20Lab/CSG-API/master/src/main/resources/wsdl/soa/QueryIdentity_V1.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/project/Git%20Lab/CSG-API/master/src/main/resources/wsdl/soa/QueryIdentity_V1.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        QUERYIDENTITYIDMDBREQABCSIMPLBINDINGQSSERVICE_WSDL_LOCATION = url;
    }

    public QueryIdentityIDMDBReqABCSImplBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryIdentityIDMDBReqABCSImplBindingQSService() {
        super(QUERYIDENTITYIDMDBREQABCSIMPLBINDINGQSSERVICE_WSDL_LOCATION, new QName("http://charter.com/enterprise/customer/QueryIdentity", "QueryIdentityIDMDBReqABCSImplBindingQSService"));
    }

    /**
     * 
     * @return
     *     returns QueryIdentityIDMDBReqABCSImpl
     */
    @WebEndpoint(name = "QueryIdentityIDMDBReqABCSImplBindingQSPort")
    public QueryIdentityIDMDBReqABCSImpl getQueryIdentityIDMDBReqABCSImplBindingQSPort() {
        return super.getPort(new QName("http://charter.com/enterprise/customer/QueryIdentity", "QueryIdentityIDMDBReqABCSImplBindingQSPort"), QueryIdentityIDMDBReqABCSImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryIdentityIDMDBReqABCSImpl
     */
    @WebEndpoint(name = "QueryIdentityIDMDBReqABCSImplBindingQSPort")
    public QueryIdentityIDMDBReqABCSImpl getQueryIdentityIDMDBReqABCSImplBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://charter.com/enterprise/customer/QueryIdentity", "QueryIdentityIDMDBReqABCSImplBindingQSPort"), QueryIdentityIDMDBReqABCSImpl.class, features);
    }

}
