
package com.charter.enterprise.billing.csg.accounts;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AccountService", targetNamespace = "http://charter.com/enterprise/billing/csg/accounts")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountService {


    /**
     * 
     * @param getAccountsRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.accounts.GetAccountsResponse
     */
    @WebMethod(operationName = "GetAccounts", action = "http://charter.com/enterprise/billing/csg/accounts:getAccountsIn")
    @WebResult(name = "GetAccountsResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/accounts", partName = "GetAccountsResult")
    public GetAccountsResponse getAccounts(
        @WebParam(name = "GetAccountsRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/accounts", partName = "getAccountsRequest")
        GetAccountsRequest getAccountsRequest);

    /**
     * 
     * @param updateAccountRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.accounts.UpdateAccountResponse
     */
    @WebMethod(operationName = "UpdateAccount", action = "http://charter.com/enterprise/billing/csg/accounts:updateAccountIn")
    @WebResult(name = "UpdateAccountResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/accounts", partName = "UpdateAccountResult")
    public UpdateAccountResponse updateAccount(
        @WebParam(name = "UpdateAccountRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/accounts", partName = "updateAccountRequest")
        UpdateAccountRequest updateAccountRequest);

    /**
     * 
     * @param updateAccountServicePriceRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.accounts.UpdateAccountServicePriceResponse
     */
    @WebMethod(operationName = "UpdateAccountServicePrice", action = "http://charter.com/enterprise/billing/csg/accounts:updateAccountServicePriceIn")
    @WebResult(name = "UpdateAccountServicePriceResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/accounts", partName = "UpdateAccountServicePriceResult")
    public UpdateAccountServicePriceResponse updateAccountServicePrice(
        @WebParam(name = "UpdateAccountServicePriceRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/accounts", partName = "updateAccountServicePriceRequest")
        UpdateAccountServicePriceRequest updateAccountServicePriceRequest);

    /**
     * 
     * @param getCPNIVerificationRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.accounts.GetCPNIVerificationResponse
     */
    @WebMethod(operationName = "GetCPNIVerification", action = "http://charter.com/enterprise/billing/csg/accounts:getCPNIVerificationIn")
    @WebResult(name = "GetCPNIVerificationResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/accounts", partName = "GetCPNIVerificationResult")
    public GetCPNIVerificationResponse getCPNIVerification(
        @WebParam(name = "GetCPNIVerificationRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/accounts", partName = "getCPNIVerificationRequest")
        GetCPNIVerificationRequest getCPNIVerificationRequest);

    /**
     * 
     * @param getAccountStatementsAllRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.accounts.GetAccountStatementsAllResponse
     */
    @WebMethod(operationName = "GetAccountStatementsAll", action = "http://charter.com/enterprise/billing/csg/accounts:getAccountStatementsAllIn")
    @WebResult(name = "GetAccountStatementsAllResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/accounts", partName = "GetAccountStatementsAllResult")
    public GetAccountStatementsAllResponse getAccountStatementsAll(
        @WebParam(name = "GetAccountStatementsAllRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/accounts", partName = "getAccountStatementsAllRequest")
        GetAccountStatementsAllRequest getAccountStatementsAllRequest);

    /**
     * 
     * @param getEquifaxCreditDetailRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.accounts.GetEquifaxCreditDataResponse
     */
    @WebMethod(operationName = "GetEquifaxCreditDetail", action = "http://charter.com/enterprise/billing/csg/accounts:getEquifaxCreditDetailIn")
    @WebResult(name = "GetEquifaxCreditDataResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/accounts", partName = "GetEquifaxCreditDetailResult")
    public GetEquifaxCreditDataResponse getEquifaxCreditDetail(
        @WebParam(name = "GetEquifaxCreditDetailRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/accounts", partName = "getEquifaxCreditDetailRequest")
        GetEquifaxCreditDetailRequest getEquifaxCreditDetailRequest);

    /**
     * 
     * @param getCustomerStatementsRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.accounts.GetCustomerStatementsResponse
     */
    @WebMethod(operationName = "GetCustomerStatements", action = "http://charter.com/enterprise/billing/csg/accounts:getCustomerStatementsIn")
    @WebResult(name = "GetCustomerStatementsResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/accounts", partName = "GetCustomerStatementsResult")
    public GetCustomerStatementsResponse getCustomerStatements(
        @WebParam(name = "GetCustomerStatementsRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/accounts", partName = "getCustomerStatementsRequest")
        GetCustomerStatementsRequest getCustomerStatementsRequest);

    /**
     * 
     * @param getAccountLedgersRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.accounts.GetAccountLedgersResponse
     */
    @WebMethod(operationName = "GetAccountLedgers", action = "http://charter.com/enterprise/billing/csg/accounts:getAccountLedgersIn")
    @WebResult(name = "GetAccountLedgersResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/accounts", partName = "GetAccountLedgersResult")
    public GetAccountLedgersResponse getAccountLedgers(
        @WebParam(name = "GetAccountLedgersRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/accounts", partName = "getAccountLedgersRequest")
        GetAccountLedgersRequest getAccountLedgersRequest);

    /**
     * 
     * @param getFutureStatementsRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.accounts.GetFutureStatementsResponse
     */
    @WebMethod(operationName = "GetFutureStatements", action = "http://charter.com/enterprise/billing/csg/accounts:getFutureStatementsIn")
    @WebResult(name = "GetFutureStatementsResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/accounts", partName = "GetFutureStatementsResult")
    public GetFutureStatementsResponse getFutureStatements(
        @WebParam(name = "GetFutureStatementsRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/accounts", partName = "getFutureStatementsRequest")
        GetFutureStatementsRequest getFutureStatementsRequest);

    /**
     * 
     * @param getVerificationRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.accounts.GetVerificationResponse
     */
    @WebMethod(operationName = "GetVerification", action = "http://charter.com/enterprise/billing/csg/accounts:getVerificationIn")
    @WebResult(name = "GetVerificationResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/accounts", partName = "GetVerificationResult")
    public GetVerificationResponse getVerification(
        @WebParam(name = "GetVerificationRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/accounts", partName = "getVerificationRequest")
        GetVerificationRequest getVerificationRequest);

}
