
package com.charter.enterprise.billing.equipment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.charter.enterprise.billing.csg.equipment.ExchangeEquipmentRequest;
import com.charter.enterprise.billing.csg.equipment.ExchangeEquipmentResponse;
import com.charter.enterprise.billing.csg.equipment.GetEquipmentInventoryRequest;
import com.charter.enterprise.billing.csg.equipment.GetEquipmentInventoryResponse;
import com.charter.enterprise.billing.csg.equipment.GetEquipmentRequest;
import com.charter.enterprise.billing.csg.equipment.GetEquipmentResponse;
import com.charter.enterprise.billing.csg.equipment.InitializeEquipmentRequest;
import com.charter.enterprise.billing.csg.equipment.InitializeEquipmentResponse;
import com.charter.enterprise.billing.csg.equipment.UpdateEquipmentInventoryRequest;
import com.charter.enterprise.billing.csg.equipment.UpdateEquipmentInventoryResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EquipmentService", targetNamespace = "http://charter.com/enterprise/billing/equipment")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.charter.enterprise.billing.equipment.ObjectFactory.class,
    com.charter.enterprise.billing.csg.equipment.ObjectFactory.class
})
public interface EquipmentService {


    /**
     * 
     * @param exchangeEquipmentRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.equipment.ExchangeEquipmentResponse
     */
    @WebMethod(operationName = "ExchangeEquipment", action = "http://charter.com/enterprise/billing/csg/equipment:exchangeEquipmentIn")
    @WebResult(name = "ExchangeEquipmentResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/equipment", partName = "ExchangeEquipmentResult")
    public ExchangeEquipmentResponse exchangeEquipment(
        @WebParam(name = "ExchangeEquipmentRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/equipment", partName = "exchangeEquipmentRequest")
        ExchangeEquipmentRequest exchangeEquipmentRequest);

    /**
     * 
     * @param getEquipmentRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.equipment.GetEquipmentResponse
     */
    @WebMethod(operationName = "GetEquipment", action = "http://charter.com/enterprise/billing/equipment:getEquipmentIn")
    @WebResult(name = "GetEquipmentResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/equipment", partName = "GetEquipmentResult")
    public GetEquipmentResponse getEquipment(
        @WebParam(name = "GetEquipmentRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/equipment", partName = "getEquipmentRequest")
        GetEquipmentRequest getEquipmentRequest);

    /**
     * 
     * @param initializeEquipmentRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.equipment.InitializeEquipmentResponse
     */
    @WebMethod(operationName = "InitializeEquipment", action = "http://charter.com/enterprise/billing/csg/equipment:initializeEquipmentIn")
    @WebResult(name = "InitializeEquipmentResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/equipment", partName = "InitializeEquipmentResult")
    public InitializeEquipmentResponse initializeEquipment(
        @WebParam(name = "InitializeEquipmentRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/equipment", partName = "initializeEquipmentRequest")
        InitializeEquipmentRequest initializeEquipmentRequest);

    /**
     * 
     * @param getEquipmentInventoryRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.equipment.GetEquipmentInventoryResponse
     */
    @WebMethod(operationName = "GetEquipmentInventory", action = "http://charter.com/enterprise/billing/csg/equipment:getEquipmentInventoryIn")
    @WebResult(name = "GetEquipmentInventoryResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/equipment", partName = "GetEquipmentInventoryResult")
    public GetEquipmentInventoryResponse getEquipmentInventory(
        @WebParam(name = "GetEquipmentInventoryRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/equipment", partName = "getEquipmentInventoryRequest")
        GetEquipmentInventoryRequest getEquipmentInventoryRequest);

    /**
     * 
     * @param updateEquipmentInventoryRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.equipment.UpdateEquipmentInventoryResponse
     */
    @WebMethod(operationName = "UpdateEquipmentInventory", action = "http://charter.com/enterprise/billing/csg/equipment:updateEquipmentInventoryIn")
    @WebResult(name = "UpdateEquipmentInventoryResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/equipment", partName = "UpdateEquipmentInventoryResult")
    public UpdateEquipmentInventoryResponse updateEquipmentInventory(
        @WebParam(name = "UpdateEquipmentInventoryRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/equipment", partName = "updateEquipmentInventoryRequest")
        UpdateEquipmentInventoryRequest updateEquipmentInventoryRequest);

}
