
package com.charter.enterprise.billing.csg.orders;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "OrderService", targetNamespace = "http://charter.com/enterprise/billing/csg/orders")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderService {


    /**
     * 
     * @param addPPVOrderRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.orders.AddPPVOrderResponse
     */
    @WebMethod(operationName = "AddPPVOrder", action = "http://charter.com/enterprise/billing/csg/orders:addPPVOrderIn")
    @WebResult(name = "AddPPVOrderResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "AddPPVOrderResult")
    public AddPPVOrderResponse addPPVOrder(
        @WebParam(name = "AddPPVOrderRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "addPPVOrderRequest")
        AddPPVOrderRequest addPPVOrderRequest);

    /**
     * 
     * @param addTivoOrderRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.orders.AddTivoOrderResponse
     */
    @WebMethod(operationName = "AddTivoOrder", action = "http://charter.com/enterprise/billing/csg/orders:addTivoOrderIn")
    @WebResult(name = "AddTivoOrderResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "AddTivoOrderResult")
    public AddTivoOrderResponse addTivoOrder(
        @WebParam(name = "AddTivoOrderRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "addTivoOrderRequest")
        AddTivoOrderRequest addTivoOrderRequest);

    /**
     * 
     * @param getOrdersRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.orders.GetOrdersResponse
     */
    @WebMethod(operationName = "GetOrders", action = "http://charter.com/enterprise/billing/csg/orders:getOrdersIn")
    @WebResult(name = "GetOrdersResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "GetOrdersResult")
    public GetOrdersResponse getOrders(
        @WebParam(name = "GetOrdersRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "getOrdersRequest")
        GetOrdersRequest getOrdersRequest);

    /**
     * 
     * @param addOrderRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.orders.AddOrderResponse
     */
    @WebMethod(operationName = "AddOrder", action = "http://charter.com/enterprise/billing/csg/orders:addOrderIn")
    @WebResult(name = "AddOrderResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "AddOrderResult")
    public AddOrderResponse addOrder(
        @WebParam(name = "AddOrderRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "addOrderRequest")
        AddOrderRequest addOrderRequest);

    /**
     * 
     * @param getOrderScheduleRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.orders.GetOrderScheduleResponse
     */
    @WebMethod(operationName = "GetOrderSchedule", action = "http://charter.com/enterprise/billing/csg/orders:getOrderScheduleIn")
    @WebResult(name = "GetOrderScheduleResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "GetOrderScheduleResult")
    public GetOrderScheduleResponse getOrderSchedule(
        @WebParam(name = "GetOrderScheduleRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "getOrderScheduleRequest")
        GetOrderScheduleRequest getOrderScheduleRequest);

    /**
     * 
     * @param deleteOrderRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.orders.DeleteOrderResponse
     */
    @WebMethod(operationName = "DeleteOrder", action = "http://charter.com/enterprise/billing/csg/orders:deleteOrderIn")
    @WebResult(name = "DeleteOrderResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "DeleteOrderResult")
    public DeleteOrderResponse deleteOrder(
        @WebParam(name = "DeleteOrderRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "deleteOrderRequest")
        DeleteOrderRequest deleteOrderRequest);

    /**
     * 
     * @param addOrderScheduleRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.orders.AddOrderScheduleResponse
     */
    @WebMethod(operationName = "AddOrderSchedule", action = "http://charter.com/enterprise/billing/csg/orders:addOrderScheduleIn")
    @WebResult(name = "AddOrderScheduleResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "AddOrderScheduleResult")
    public AddOrderScheduleResponse addOrderSchedule(
        @WebParam(name = "AddOrderScheduleRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "addOrderScheduleRequest")
        AddOrderScheduleRequest addOrderScheduleRequest);

    /**
     * 
     * @param updateSpecialRequestOrderRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.orders.UpdateSpecialRequestOrderResponse
     */
    @WebMethod(operationName = "UpdateSpecialRequestOrder", action = "http://charter.com/enterprise/billing/csg/orders:updateSpecialRequestOrderIn")
    @WebResult(name = "UpdateSpecialRequestOrderResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "UpdateSpecialRequestOrderResult")
    public UpdateSpecialRequestOrderResponse updateSpecialRequestOrder(
        @WebParam(name = "UpdateSpecialRequestOrderRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "updateSpecialRequestOrderRequest")
        UpdateSpecialRequestOrderRequest updateSpecialRequestOrderRequest);

    /**
     * 
     * @param getAvailableNumbersRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.orders.GetAvailableNumbersResponse
     */
    @WebMethod(operationName = "GetAvailableNumbers", action = "http://charter.com/enterprise/billing/csg/orders:getAvailableNumbersIn")
    @WebResult(name = "GetAvailableNumbersResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "GetAvailableNumbersResult")
    public GetAvailableNumbersResponse getAvailableNumbers(
        @WebParam(name = "getAvailableNumbersRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "getAvailableNumbersRequest")
        GetAvailableNumbersRequest getAvailableNumbersRequest);

    /**
     * 
     * @param getAssignedTelephoneNumberListRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.orders.GetAssignedTelephoneNumberListResponse
     */
    @WebMethod(operationName = "GetAssignedTelephoneNumberList", action = "http://charter.com/enterprise/billing/csg/orders:getAssignedTelephoneNumberListIn")
    @WebResult(name = "GetAssignedTelephoneNumberListResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "GetAssignedTelephoneNumberListResult")
    public GetAssignedTelephoneNumberListResponse getAssignedTelephoneNumberList(
        @WebParam(name = "GetAssignedTelephoneNumberListRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "getAssignedTelephoneNumberListRequest")
        GetAssignedTelephoneNumberListRequest getAssignedTelephoneNumberListRequest);

    /**
     * 
     * @param getAvailableVoiceProductsRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.orders.GetAvailableVoiceProductsResponse
     */
    @WebMethod(operationName = "GetAvailableVoiceProducts", action = "http://charter.com/enterprise/billing/csg/orders:getAvailableVoiceProductListIn")
    @WebResult(name = "GetAvailableVoiceProductsResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/orders.gavpl", partName = "GetAvailableVoiceProductsResult")
    public GetAvailableVoiceProductsResponse getAvailableVoiceProducts(
        @WebParam(name = "getAvailableVoiceProductsRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "getAvailableVoiceProductsRequest")
        GetAvailableVoiceProductsRequest getAvailableVoiceProductsRequest);

    /**
     * 
     * @param updateOrderRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.orders.UpdateOrderResponse
     */
    @WebMethod(operationName = "UpdateOrder", action = "http://charter.com/enterprise/billing/csg/orders:updateOrderRequestIn")
    @WebResult(name = "UpdateOrderResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "UpdateOrderResult")
    public UpdateOrderResponse updateOrder(
        @WebParam(name = "UpdateOrderRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "updateOrderRequest")
        UpdateOrderRequest updateOrderRequest);

    /**
     * 
     * @param getScheduleListRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.orders.GetScheduleListResponse
     */
    @WebMethod(operationName = "GetScheduleList", action = "http://charter.com/enterprise/billing/csg/orders:getScheduleListRequestIn")
    @WebResult(name = "GetScheduleListResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "GetScheduleListResult")
    public GetScheduleListResponse getScheduleList(
        @WebParam(name = "GetScheduleListRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "getScheduleListRequest")
        GetScheduleListRequest getScheduleListRequest);

    /**
     * 
     * @param updateScheduleRequest
     * @return
     *     returns com.charter.enterprise.billing.csg.orders.UpdateScheduleResponse
     */
    @WebMethod(operationName = "UpdateSchedule", action = "http://charter.com/enterprise/billing/csg/orders:updateScheduleRequestIn")
    @WebResult(name = "UpdateScheduleResponse", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "UpdateScheduleResult")
    public UpdateScheduleResponse updateSchedule(
        @WebParam(name = "UpdateScheduleRequest", targetNamespace = "http://charter.com/enterprise/billing/csg/orders", partName = "updateScheduleRequest")
        UpdateScheduleRequest updateScheduleRequest);

}
