
package com.charter.enterprise.prefcomm.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "EnterprisePreferredCommunicationServiceException", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1")
public class EnterprisePreferredCommunicationServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EnterprisePreferredCommunicationServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public EnterprisePreferredCommunicationServiceException_Exception(String message, EnterprisePreferredCommunicationServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public EnterprisePreferredCommunicationServiceException_Exception(String message, EnterprisePreferredCommunicationServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.charter.enterprise.prefcomm.v1.EnterprisePreferredCommunicationServiceException
     */
    public EnterprisePreferredCommunicationServiceException getFaultInfo() {
        return faultInfo;
    }

}
