
package com.charter.enterprise.prefcomm.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EnterprisePreferredCommunicationDataService", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EnterprisePreferredCommunicationDataService {


    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.GetEventCommunicationByIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getEventCommunicationByIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public GetEventCommunicationByIdResponse getEventCommunicationById(
        @WebParam(name = "getEventCommunicationById", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        GetEventCommunicationById parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindContactPreferencesByContactDataValueAndContactMethodIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findContactPreferencesByContactDataValueAndContactMethodIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindContactPreferencesByContactDataValueAndContactMethodIdResponse findContactPreferencesByContactDataValueAndContactMethodId(
        @WebParam(name = "findContactPreferencesByContactDataValueAndContactMethodId", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindContactPreferencesByContactDataValueAndContactMethodId parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.DeleteContactResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteContactResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public DeleteContactResponse deleteContact(
        @WebParam(name = "deleteContact", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        DeleteContact parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindContactDatasByContactIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findContactDatasByContactIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindContactDatasByContactIdResponse findContactDatasByContactId(
        @WebParam(name = "findContactDatasByContactId", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindContactDatasByContactId parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.GetContactTypeByIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getContactTypeByIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public GetContactTypeByIdResponse getContactTypeById(
        @WebParam(name = "getContactTypeById", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        GetContactTypeById parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.InvalidateContactResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "invalidateContactResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public InvalidateContactResponse invalidateContact(
        @WebParam(name = "invalidateContact", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        InvalidateContact parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.SaveContactPreferenceResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "saveContactPreferenceResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public SaveContactPreferenceResponse saveContactPreference(
        @WebParam(name = "saveContactPreference", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        SaveContactPreference parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindContactDatasByAccountNumberAndBillingSystemResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findContactDatasByAccountNumberAndBillingSystemResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindContactDatasByAccountNumberAndBillingSystemResponse findContactDatasByAccountNumberAndBillingSystem(
        @WebParam(name = "findContactDatasByAccountNumberAndBillingSystem", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindContactDatasByAccountNumberAndBillingSystem parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindUIEventFamilyByApplicationIDAndCustomerTypeV1X2Response
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod(operationName = "findUIEventFamilyByApplicationIDAndCustomerTypeV1x2")
    @WebResult(name = "findUIEventFamilyByApplicationIDAndCustomerTypeV1x2Response", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindUIEventFamilyByApplicationIDAndCustomerTypeV1X2Response findUIEventFamilyByApplicationIDAndCustomerTypeV1X2(
        @WebParam(name = "findUIEventFamilyByApplicationIDAndCustomerTypeV1x2", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindUIEventFamilyByApplicationIDAndCustomerTypeV1X2 parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.GetContactByUsernameResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getContactByUsernameResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public GetContactByUsernameResponse getContactByUsername(
        @WebParam(name = "getContactByUsername", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        GetContactByUsername parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.PurgePreferenceAccountResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "purgePreferenceAccountResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public PurgePreferenceAccountResponse purgePreferenceAccount(
        @WebParam(name = "purgePreferenceAccount", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        PurgePreferenceAccount parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindAllBillingSystemResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findAllBillingSystemResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindAllBillingSystemResponse findAllBillingSystem(
        @WebParam(name = "findAllBillingSystem", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindAllBillingSystem parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindPreferenceHistoryByAccountNumberInRangeResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findPreferenceHistoryByAccountNumberInRangeResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindPreferenceHistoryByAccountNumberInRangeResponse findPreferenceHistoryByAccountNumberInRange(
        @WebParam(name = "findPreferenceHistoryByAccountNumberInRange", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindPreferenceHistoryByAccountNumberInRange parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.GetServiceEventByIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getServiceEventByIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public GetServiceEventByIdResponse getServiceEventById(
        @WebParam(name = "getServiceEventById", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        GetServiceEventById parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.GetContactPreferenceByIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getContactPreferenceByIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public GetContactPreferenceByIdResponse getContactPreferenceById(
        @WebParam(name = "getContactPreferenceById", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        GetContactPreferenceById parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.PurgePreferencesResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "purgePreferencesResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public PurgePreferencesResponse purgePreferences(
        @WebParam(name = "purgePreferences", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        PurgePreferences parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.GetContactByIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getContactByIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public GetContactByIdResponse getContactById(
        @WebParam(name = "getContactById", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        GetContactById parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindContactPreferencesByContactDataResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findContactPreferencesByContactDataResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindContactPreferencesByContactDataResponse findContactPreferencesByContactData(
        @WebParam(name = "findContactPreferencesByContactData", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindContactPreferencesByContactData parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.SaveContactDatasResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "saveContactDatasResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public SaveContactDatasResponse saveContactDatas(
        @WebParam(name = "saveContactDatas", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        SaveContactDatas parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindContactsByAccountNumberAndBillingSystemAndRoleResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findContactsByAccountNumberAndBillingSystemAndRoleResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindContactsByAccountNumberAndBillingSystemAndRoleResponse findContactsByAccountNumberAndBillingSystemAndRole(
        @WebParam(name = "findContactsByAccountNumberAndBillingSystemAndRole", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindContactsByAccountNumberAndBillingSystemAndRole parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindUIEventFamilyByApplicationIDV1X2Response
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod(operationName = "findUIEventFamilyByApplicationIDV1x2")
    @WebResult(name = "findUIEventFamilyByApplicationIDV1x2Response", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindUIEventFamilyByApplicationIDV1X2Response findUIEventFamilyByApplicationIDV1X2(
        @WebParam(name = "findUIEventFamilyByApplicationIDV1x2", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindUIEventFamilyByApplicationIDV1X2 parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.GetLanguageTypeByIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getLanguageTypeByIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public GetLanguageTypeByIdResponse getLanguageTypeById(
        @WebParam(name = "getLanguageTypeById", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        GetLanguageTypeById parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindPreferenceHistoryByAccountNumberResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findPreferenceHistoryByAccountNumberResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindPreferenceHistoryByAccountNumberResponse findPreferenceHistoryByAccountNumber(
        @WebParam(name = "findPreferenceHistoryByAccountNumber", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindPreferenceHistoryByAccountNumber parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.GetPreferenceAccountByAccountNumberAndBillingSystemResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getPreferenceAccountByAccountNumberAndBillingSystemResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public GetPreferenceAccountByAccountNumberAndBillingSystemResponse getPreferenceAccountByAccountNumberAndBillingSystem(
        @WebParam(name = "getPreferenceAccountByAccountNumberAndBillingSystem", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        GetPreferenceAccountByAccountNumberAndBillingSystem parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindContactsByAccountNumberAndBillingSystemResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findContactsByAccountNumberAndBillingSystemResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindContactsByAccountNumberAndBillingSystemResponse findContactsByAccountNumberAndBillingSystem(
        @WebParam(name = "findContactsByAccountNumberAndBillingSystem", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindContactsByAccountNumberAndBillingSystem parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.GetUIEventFamilyByApplicationIdAndServiceEventIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getUIEventFamilyByApplicationIdAndServiceEventIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public GetUIEventFamilyByApplicationIdAndServiceEventIdResponse getUIEventFamilyByApplicationIdAndServiceEventId(
        @WebParam(name = "getUIEventFamilyByApplicationIdAndServiceEventId", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        GetUIEventFamilyByApplicationIdAndServiceEventId parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.SaveContactByContactValuesResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "saveContactByContactValuesResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public SaveContactByContactValuesResponse saveContactByContactValues(
        @WebParam(name = "saveContactByContactValues", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        SaveContactByContactValues parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindContactPreferencesByPreferenceAccountAndContactMethodResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findContactPreferencesByPreferenceAccountAndContactMethodResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindContactPreferencesByPreferenceAccountAndContactMethodResponse findContactPreferencesByPreferenceAccountAndContactMethod(
        @WebParam(name = "findContactPreferencesByPreferenceAccountAndContactMethod", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindContactPreferencesByPreferenceAccountAndContactMethod parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.OptOutResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "optOutResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public OptOutResponse optOut(
        @WebParam(name = "optOut", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        OptOut parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.GetPreferenceAccountByAccountIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getPreferenceAccountByAccountIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public GetPreferenceAccountByAccountIdResponse getPreferenceAccountByAccountId(
        @WebParam(name = "getPreferenceAccountByAccountId", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        GetPreferenceAccountByAccountId parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.PurgeAccountResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "purgeAccountResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public PurgeAccountResponse purgeAccount(
        @WebParam(name = "purgeAccount", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        PurgeAccount parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.SavePreferenceAccountResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "savePreferenceAccountResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public SavePreferenceAccountResponse savePreferenceAccount(
        @WebParam(name = "savePreferenceAccount", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        SavePreferenceAccount parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindAllUIEventFamiliesResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findAllUIEventFamiliesResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindAllUIEventFamiliesResponse findAllUIEventFamilies(
        @WebParam(name = "findAllUIEventFamilies", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindAllUIEventFamilies parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindAllServiceEventsResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findAllServiceEventsResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindAllServiceEventsResponse findAllServiceEvents(
        @WebParam(name = "findAllServiceEvents", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindAllServiceEvents parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.GetUIApplicationByIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getUIApplicationByIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public GetUIApplicationByIdResponse getUIApplicationById(
        @WebParam(name = "getUIApplicationById", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        GetUIApplicationById parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindContactHistoryByAccountNumberResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findContactHistoryByAccountNumberResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindContactHistoryByAccountNumberResponse findContactHistoryByAccountNumber(
        @WebParam(name = "findContactHistoryByAccountNumber", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindContactHistoryByAccountNumber parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.DeleteContactDataByIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteContactDataByIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public DeleteContactDataByIdResponse deleteContactDataById(
        @WebParam(name = "deleteContactDataById", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        DeleteContactDataById parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.GetContactRoleByIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getContactRoleByIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public GetContactRoleByIdResponse getContactRoleById(
        @WebParam(name = "getContactRoleById", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        GetContactRoleById parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.SaveContactDataByValueResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "saveContactDataByValueResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public SaveContactDataByValueResponse saveContactDataByValue(
        @WebParam(name = "saveContactDataByValue", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        SaveContactDataByValue parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindContactDatasByAccountNumberAndBillingSystemAndRoleResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findContactDatasByAccountNumberAndBillingSystemAndRoleResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindContactDatasByAccountNumberAndBillingSystemAndRoleResponse findContactDatasByAccountNumberAndBillingSystemAndRole(
        @WebParam(name = "findContactDatasByAccountNumberAndBillingSystemAndRole", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindContactDatasByAccountNumberAndBillingSystemAndRole parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindContactPreferencesByPreferenceAccountAndServiceEventResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findContactPreferencesByPreferenceAccountAndServiceEventResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindContactPreferencesByPreferenceAccountAndServiceEventResponse findContactPreferencesByPreferenceAccountAndServiceEvent(
        @WebParam(name = "findContactPreferencesByPreferenceAccountAndServiceEvent", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindContactPreferencesByPreferenceAccountAndServiceEvent parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindContactsByPreferenceAccountAndContactRoleResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findContactsByPreferenceAccountAndContactRoleResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindContactsByPreferenceAccountAndContactRoleResponse findContactsByPreferenceAccountAndContactRole(
        @WebParam(name = "findContactsByPreferenceAccountAndContactRole", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindContactsByPreferenceAccountAndContactRole parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.GetContactMethodByIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getContactMethodByIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public GetContactMethodByIdResponse getContactMethodById(
        @WebParam(name = "getContactMethodById", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        GetContactMethodById parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.SaveContactDataResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "saveContactDataResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public SaveContactDataResponse saveContactData(
        @WebParam(name = "saveContactData", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        SaveContactData parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindContactPreferencesByContactDataValueResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findContactPreferencesByContactDataValueResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindContactPreferencesByContactDataValueResponse findContactPreferencesByContactDataValue(
        @WebParam(name = "findContactPreferencesByContactDataValue", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindContactPreferencesByContactDataValue parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.SaveContactPreferenceByValuesResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "saveContactPreferenceByValuesResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public SaveContactPreferenceByValuesResponse saveContactPreferenceByValues(
        @WebParam(name = "saveContactPreferenceByValues", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        SaveContactPreferenceByValues parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.DeleteContactByContactIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteContactByContactIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public DeleteContactByContactIdResponse deleteContactByContactId(
        @WebParam(name = "deleteContactByContactId", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        DeleteContactByContactId parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindAllContactRolesResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findAllContactRolesResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindAllContactRolesResponse findAllContactRoles(
        @WebParam(name = "findAllContactRoles", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindAllContactRoles parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.SaveContactsByContactValuesResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "saveContactsByContactValuesResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public SaveContactsByContactValuesResponse saveContactsByContactValues(
        @WebParam(name = "saveContactsByContactValues", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        SaveContactsByContactValues parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindAllLanguageTypesResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findAllLanguageTypesResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindAllLanguageTypesResponse findAllLanguageTypes(
        @WebParam(name = "findAllLanguageTypes", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindAllLanguageTypes parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindContactPreferencesByPreferenceAccountResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findContactPreferencesByPreferenceAccountResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindContactPreferencesByPreferenceAccountResponse findContactPreferencesByPreferenceAccount(
        @WebParam(name = "findContactPreferencesByPreferenceAccount", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindContactPreferencesByPreferenceAccount parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.DeleteContactPreferenceResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteContactPreferenceResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public DeleteContactPreferenceResponse deleteContactPreference(
        @WebParam(name = "deleteContactPreference", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        DeleteContactPreference parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindContactPreferencesByAccountNumberAndBillingSystemResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findContactPreferencesByAccountNumberAndBillingSystemResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindContactPreferencesByAccountNumberAndBillingSystemResponse findContactPreferencesByAccountNumberAndBillingSystem(
        @WebParam(name = "findContactPreferencesByAccountNumberAndBillingSystem", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindContactPreferencesByAccountNumberAndBillingSystem parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindContactDataByPreferenceAccountAndContactRoleResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findContactDataByPreferenceAccountAndContactRoleResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindContactDataByPreferenceAccountAndContactRoleResponse findContactDataByPreferenceAccountAndContactRole(
        @WebParam(name = "findContactDataByPreferenceAccountAndContactRole", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindContactDataByPreferenceAccountAndContactRole parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindAllModifiedContactAccountsInRangeResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findAllModifiedContactAccountsInRangeResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindAllModifiedContactAccountsInRangeResponse findAllModifiedContactAccountsInRange(
        @WebParam(name = "findAllModifiedContactAccountsInRange", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindAllModifiedContactAccountsInRange parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.SaveContactsResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "saveContactsResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public SaveContactsResponse saveContacts(
        @WebParam(name = "saveContacts", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        SaveContacts parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindContactDataByPreferenceAccountResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findContactDataByPreferenceAccountResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindContactDataByPreferenceAccountResponse findContactDataByPreferenceAccount(
        @WebParam(name = "findContactDataByPreferenceAccount", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindContactDataByPreferenceAccount parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.GetBillingSystemByIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getBillingSystemByIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public GetBillingSystemByIdResponse getBillingSystemById(
        @WebParam(name = "getBillingSystemById", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        GetBillingSystemById parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.GetEventCommunicationByApplicationIdServiceEventIdAndContactMethodIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getEventCommunicationByApplicationIdServiceEventIdAndContactMethodIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public GetEventCommunicationByApplicationIdServiceEventIdAndContactMethodIdResponse getEventCommunicationByApplicationIdServiceEventIdAndContactMethodId(
        @WebParam(name = "getEventCommunicationByApplicationIdServiceEventIdAndContactMethodId", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        GetEventCommunicationByApplicationIdServiceEventIdAndContactMethodId parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.DeleteContactPreferenceByIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteContactPreferenceByIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public DeleteContactPreferenceByIdResponse deleteContactPreferenceById(
        @WebParam(name = "deleteContactPreferenceById", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        DeleteContactPreferenceById parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindContactsByPreferenceAccountResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findContactsByPreferenceAccountResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindContactsByPreferenceAccountResponse findContactsByPreferenceAccount(
        @WebParam(name = "findContactsByPreferenceAccount", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindContactsByPreferenceAccount parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.GetPreferenceAccountInfoByAccountNumberAndBillingSystemResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getPreferenceAccountInfoByAccountNumberAndBillingSystemResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public GetPreferenceAccountInfoByAccountNumberAndBillingSystemResponse getPreferenceAccountInfoByAccountNumberAndBillingSystem(
        @WebParam(name = "getPreferenceAccountInfoByAccountNumberAndBillingSystem", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        GetPreferenceAccountInfoByAccountNumberAndBillingSystem parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindAllContactMethodsResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findAllContactMethodsResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindAllContactMethodsResponse findAllContactMethods(
        @WebParam(name = "findAllContactMethods", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindAllContactMethods parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindUIEventFamilyByApplicationIDAndCustomerTypeResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findUIEventFamilyByApplicationIDAndCustomerTypeResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindUIEventFamilyByApplicationIDAndCustomerTypeResponse findUIEventFamilyByApplicationIDAndCustomerType(
        @WebParam(name = "findUIEventFamilyByApplicationIDAndCustomerType", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindUIEventFamilyByApplicationIDAndCustomerType parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.SaveContactPreferenceByValueResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "saveContactPreferenceByValueResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public SaveContactPreferenceByValueResponse saveContactPreferenceByValue(
        @WebParam(name = "saveContactPreferenceByValue", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        SaveContactPreferenceByValue parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindAllUIApplicationsResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findAllUIApplicationsResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindAllUIApplicationsResponse findAllUIApplications(
        @WebParam(name = "findAllUIApplications", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindAllUIApplications parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.SaveContactPreferencesResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "saveContactPreferencesResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public SaveContactPreferencesResponse saveContactPreferences(
        @WebParam(name = "saveContactPreferences", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        SaveContactPreferences parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindAllModifiedPreferenceAccountsInRangeResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findAllModifiedPreferenceAccountsInRangeResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindAllModifiedPreferenceAccountsInRangeResponse findAllModifiedPreferenceAccountsInRange(
        @WebParam(name = "findAllModifiedPreferenceAccountsInRange", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindAllModifiedPreferenceAccountsInRange parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindContactDataByContactDataValueResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findContactDataByContactDataValueResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindContactDataByContactDataValueResponse findContactDataByContactDataValue(
        @WebParam(name = "findContactDataByContactDataValue", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindContactDataByContactDataValue parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.GetPreferenceAccountByIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getPreferenceAccountByIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public GetPreferenceAccountByIdResponse getPreferenceAccountById(
        @WebParam(name = "getPreferenceAccountById", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        GetPreferenceAccountById parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindContactHistoryByAccountNumberInRangeResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findContactHistoryByAccountNumberInRangeResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindContactHistoryByAccountNumberInRangeResponse findContactHistoryByAccountNumberInRange(
        @WebParam(name = "findContactHistoryByAccountNumberInRange", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindContactHistoryByAccountNumberInRange parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.GetContactDataByIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getContactDataByIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public GetContactDataByIdResponse getContactDataById(
        @WebParam(name = "getContactDataById", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        GetContactDataById parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.PurgePreferenceAccountByPreferenceAccountIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "purgePreferenceAccountByPreferenceAccountIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public PurgePreferenceAccountByPreferenceAccountIdResponse purgePreferenceAccountByPreferenceAccountId(
        @WebParam(name = "purgePreferenceAccountByPreferenceAccountId", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        PurgePreferenceAccountByPreferenceAccountId parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindAllContactTypesResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findAllContactTypesResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindAllContactTypesResponse findAllContactTypes(
        @WebParam(name = "findAllContactTypes", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindAllContactTypes parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindAllEventCommunicationsResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findAllEventCommunicationsResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindAllEventCommunicationsResponse findAllEventCommunications(
        @WebParam(name = "findAllEventCommunications", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindAllEventCommunications parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.GetUIEventFamilyByIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getUIEventFamilyByIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public GetUIEventFamilyByIdResponse getUIEventFamilyById(
        @WebParam(name = "getUIEventFamilyById", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        GetUIEventFamilyById parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.SavePreferenceAccountByValuesResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "savePreferenceAccountByValuesResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public SavePreferenceAccountByValuesResponse savePreferenceAccountByValues(
        @WebParam(name = "savePreferenceAccountByValues", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        SavePreferenceAccountByValues parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindContactDatasByContactResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findContactDatasByContactResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindContactDatasByContactResponse findContactDatasByContact(
        @WebParam(name = "findContactDatasByContact", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindContactDatasByContact parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindUIEventFamilyByApplicationIDResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findUIEventFamilyByApplicationIDResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindUIEventFamilyByApplicationIDResponse findUIEventFamilyByApplicationID(
        @WebParam(name = "findUIEventFamilyByApplicationID", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindUIEventFamilyByApplicationID parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.SaveContactResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "saveContactResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public SaveContactResponse saveContact(
        @WebParam(name = "saveContact", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        SaveContact parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.GetContactByNameIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getContactByNameIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public GetContactByNameIdResponse getContactByNameId(
        @WebParam(name = "getContactByNameId", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        GetContactByNameId parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.DeleteContactDataResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteContactDataResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public DeleteContactDataResponse deleteContactData(
        @WebParam(name = "deleteContactData", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        DeleteContactData parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindEventCommunicationsByApplicationIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findEventCommunicationsByApplicationIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindEventCommunicationsByApplicationIdResponse findEventCommunicationsByApplicationId(
        @WebParam(name = "findEventCommunicationsByApplicationId", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindEventCommunicationsByApplicationId parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.SaveContactDatasByValuesListResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "saveContactDatasByValuesListResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public SaveContactDatasByValuesListResponse saveContactDatasByValuesList(
        @WebParam(name = "saveContactDatasByValuesList", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        SaveContactDatasByValuesList parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

    /**
     * 
     * @param charterHeaderInputInfo
     * @param parameters
     * @return
     *     returns com.charter.enterprise.prefcomm.v1.FindEventCommunicationByApplicationIdAndServiceEventIdResponse
     * @throws EnterprisePreferredCommunicationServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "findEventCommunicationByApplicationIdAndServiceEventIdResponse", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
    public FindEventCommunicationByApplicationIdAndServiceEventIdResponse findEventCommunicationByApplicationIdAndServiceEventId(
        @WebParam(name = "findEventCommunicationByApplicationIdAndServiceEventId", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", partName = "parameters")
        FindEventCommunicationByApplicationIdAndServiceEventId parameters,
        @WebParam(name = "charterHeaderInputInfo", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", header = true, partName = "charterHeaderInputInfo")
        StandardInputHeader charterHeaderInputInfo)
        throws EnterprisePreferredCommunicationServiceException_Exception
    ;

}
