
package com.charter.enterprise.prefcomm.v1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EnterprisePreferredCommunicationSoapEndpointImplService", targetNamespace = "http://www.charter.com/enterprise/prefcomm/v1", wsdlLocation = "file:/D:/project/Git%20Lab/CSG-API/src/main/resources/wsdl/prefcomm/prefcomm.wsdl")
public class EnterprisePreferredCommunicationSoapEndpointImplService
    extends Service
{

    private final static URL ENTERPRISEPREFERREDCOMMUNICATIONSOAPENDPOINTIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.charter.enterprise.prefcomm.v1.EnterprisePreferredCommunicationSoapEndpointImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.charter.enterprise.prefcomm.v1.EnterprisePreferredCommunicationSoapEndpointImplService.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/project/Git%20Lab/CSG-API/src/main/resources/wsdl/prefcomm/prefcomm.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/project/Git%20Lab/CSG-API/src/main/resources/wsdl/prefcomm/prefcomm.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ENTERPRISEPREFERREDCOMMUNICATIONSOAPENDPOINTIMPLSERVICE_WSDL_LOCATION = url;
    }

    public EnterprisePreferredCommunicationSoapEndpointImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnterprisePreferredCommunicationSoapEndpointImplService() {
        super(ENTERPRISEPREFERREDCOMMUNICATIONSOAPENDPOINTIMPLSERVICE_WSDL_LOCATION, new QName("http://www.charter.com/enterprise/prefcomm/v1", "EnterprisePreferredCommunicationSoapEndpointImplService"));
    }

    /**
     * 
     * @return
     *     returns EnterprisePreferredCommunicationDataService
     */
    @WebEndpoint(name = "EnterprisePreferredCommunicationDataServicePort")
    public EnterprisePreferredCommunicationDataService getEnterprisePreferredCommunicationDataServicePort() {
        return super.getPort(new QName("http://www.charter.com/enterprise/prefcomm/v1", "EnterprisePreferredCommunicationDataServicePort"), EnterprisePreferredCommunicationDataService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnterprisePreferredCommunicationDataService
     */
    @WebEndpoint(name = "EnterprisePreferredCommunicationDataServicePort")
    public EnterprisePreferredCommunicationDataService getEnterprisePreferredCommunicationDataServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.charter.com/enterprise/prefcomm/v1", "EnterprisePreferredCommunicationDataServicePort"), EnterprisePreferredCommunicationDataService.class, features);
    }

}
